name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Install backend deps
              run: |
                  python -m venv .venv
                  . .venv/bin/activate
                  pip install --upgrade pip
                  pip install -r backend/requirements-dev.txt
            - name: Syntax check
              run: python -m py_compile backend/simple_app.py

    frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install frontend deps
              working-directory: frontend
              run: npm ci
